// 02-vue-router/todo/src/components/TodoFilter.vue
<template>
  <div>
    {{ left }}---
    <button
      :class="{ active: filter === 'all' }"
      @click="$emit('change-filter', 'all')"
    >
      all
    </button>
    <button
      :class="{ active: filter === 'active' }"
      @click="$emit('change-filter', 'active')"
    >
      active
    </button>
    <button
      :class="{ active: filter === 'complated' }"
      @click="$emit('change-filter', 'complated')"
    >
      complated
    </button>
  </div>
</template>

<script>
export default {
  name: "TodoFilter",
  props: ["filter", "left"],
  components: {},
};
</script>

<style>
button.active {
  background: red;
}
</style>

// 06-react/02/my-app/src/components/TodoFilter.jsx
import React from "react";

export default function TodoFilter(props) {
  return (
    <div className="todo-filter">
      {props.filters.map((filter, index) => {
        return (
          <button
            style={props.currentFilter === filter ? { color: "red" } : null}
            key={index}
            onClick={() => props.changeFilter(filter)}
          >
            {filter}
          </button>
        );
      })}
    </div>
  );
}

// All Active Completed
