// 02-vue-router/todo/src/components/TodoList.vue
<template>
  <ul>
    <TodoItem
      v-for="todo in todos"
      :key="todo.id"
      :todo="todo"
      @toggle="$emit('toggle', $event)"
      @delete-todo="$emit('delete-todo', $event)"
      @updata-todo="updataTodo"
    />

    <!-- <TodoItem
      v-for="todo in todos"
      :key="todo.id"
      :todo="todo"
      @toggle="toggle"
    /> -->
  </ul>
</template>

<script>
import TodoItem from "./TodoItem";

export default {
  name: "TodoList",
  props: ["todos"],
  components: {
    TodoItem,
  },
  methods: {
    toggle: function (a) {
      //   console.log('TodoList', a);
      this.$emit("toggle", a);
    },
    updataTodo: function (a, b) {
      // console.log(a, b);
      this.$emit("updata-todo", a, b);
    },
  },
};
</script>

<style>
</style>

// 06-react/02/my-app/src/components/TodoList.jsx
import React from "react";

import TodoItem from "../components/TodoItem";

export default function TodoList(props) {
  return (
    <ul style={{ margin: 0, padding: 0 }}>
      {props.todos.map((item) => (
        <TodoItem key={item.id} todo={item} delTodo={props.delTodo} />
      ))}
    </ul>
  );
}
