// 06-react/02/my-app/src/App.js
import "./App.css";

import NewTodo from "./components/NewTodo";
import TodoList from "./components/TodoList";
import TodoFilter from "./components/TodoFilter";

import React, { Component } from "react";

export default class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      todos: [
        { text: "学习react", complated: true, id: 1 },
        { text: "学习react-router", complated: false, id: 4 },
        { text: "学习react-create-app", complated: true, id: 2 },
      ],
      filters: ["All", "Active", "Completed"],
      currentFilter: "All",
    };
  }

  addTodo = (n) => {
    // console.log('addTodo', n);
    const id = this.state.todos.length
      ? Math.max(...this.state.todos.map((item) => item.id)) + 1
      : 1;
    this.setState((state) => ({
      todos: [...state.todos, { text: n, conplated: false, id }],
    }));
  };

  delTodo = (n) => {
    // console.log('delTodo', n);
    this.setState((state) => ({
      todos: state.todos.filter((item) => item.id !== n),
    }));
  };

  changeFilter = (filter) => {
    console.log(filter);
    this.setState({ currentFilter: filter });
  };

  render() {
    let todos;
    switch (this.state.currentFilter) {
      case "Active":
        todos = this.state.todos.filter((todo) => !todo.complated);
        console.log(todos);
        break;
      case "Completed":
        todos = this.state.todos.filter((todo) => todo.complated);
        break;
      default:
        todos = this.state.todos;
        break;
    }

    return (
      <div className="App">
        <NewTodo addTodo={this.addTodo} />
        <TodoList todos={todos} delTodo={this.delTodo} />
        <TodoFilter
          currentFilter={this.state.currentFilter}
          filters={this.state.filters}
          changeFilter={this.changeFilter}
        />
      </div>
    );
  }
}

/*

  App
  --AddTodo
  --TodoList
    --TodoItem
  --TodoFilter
*/

// 02-vue-router/todo/src/App.vue


<template>
  <!-- npm cache clean -->
  <div id="app">
    <AddTodo @add-todo="addTodo" />
    <TodoList
      :todos="currentTodos"
      @toggle="toggleHandler"
      @delete-todo="deleteTodo"
      @updata-todo="updataTodo"
    />

    <TodoFilter :filter="currentFilter" @change-filter="changeFilter" :left="activeTodos.length" />
  </div>
</template>

<script>
import AddTodo from "./components/AddTodo.vue";
import TodoList from "./components/TodoList.vue";
import TodoFilter from "./components/TodoFilter.vue";

export default {
  name: "App",
  components: {
    AddTodo,
    TodoList,
    TodoFilter,
  },
  data: function () {
    return {
      currentFilter: "all",
      todos: [
        {
          complated: false,
          text: "1111",
          id: 1,
        },
        {
          complated: true,
          text: "2222",
          id: 2,
        },
        {
          complated: false,
          text: "4444",
          id: 4,
        },
      ],
    };
  },

  computed: {
    activeTodos: function () {
      return this.todos.filter((todo) => {
        return !todo.complated;
      });
    },

    complatedTodos: function () {
      return this.todos.filter((todo) => {
        return todo.complated;
      });
    },

    currentTodos: function () {
      switch (this.currentFilter) {
        case "active":
          return this.activeTodos;
        case "complated":
          return this.complatedTodos;
        default:
          return this.todos;
      }
    },
  },

  methods: {
    toggleHandler: function (id) {
      //   console.log(a);
      this.todos = this.todos.map((todo) => {
        if (todo.id === id) {
          return { ...todo, complated: !todo.complated };
        }

        return { ...todo };
      });
    },

    addTodo: function (text) {
      console.log(text);
      this.todos.push({
        text,
        compalted: false,
        id: this.todos.length ? this.todos[this.todos.length - 1].id + 1 : 0,
      });
    },

    deleteTodo: function (id) {
      console.log("deleteTodo", id);
      this.todos = this.todos.filter((todo) => {
        return todo.id !== id;
      });
    },
    updataTodo: function (id, newText) {
      // console.log("updateTodo", a, b);
      this.todos = this.todos.map((todo) => {
        if (todo.id === id) {
          return { ...todo, text: newText };

          // todo.text = newText
          // return todo
        }
        return todo;
      });
    },
    changeFilter: function (filter) {
      this.currentFilter = filter;
    },
  },
};
</script>

<style>
</style>
