// 06-react/02/my-app/src/components/TodoItem.jsx
import React from "react";
import "./TodoItem.scss";

export default function TodoItem({ todo, delTodo }) {
  function changeHandler(e) {
    console.log(e.target.checked);
  }

  return (
    <li className="todo-item">
      <input
        type="checkbox"
        checked={todo.complated}
        onChange={changeHandler}
      />
      <span>{todo.text}</span>
      <del onClick={() => delTodo(todo.id)}>X</del>
    </li>
  );
}

// 02-vue-router/01/todo/src/components/TodoItem.vue
<template>
  <li>
    <input
      type="checkbox"
      @change="changeHandler(todo.id)"
      :checked="todo.complated"
    />
    <span :class="{ complated: todo.complated }">{{ todo.text }}</span>
    <button>X</button>
  </li>
</template>

<script>
export default {
  name: "TodoItem",
  props: ["todo"],
  methods: {
    changeHandler: function (id) {
      console.log("TodoItem", id);
      this.$emit("toggle", id);
    },
  },
};
</script>

<style>
.complated {
  text-decoration: line-through;
}
</style>
